version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.18.1
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: 'Update NPM'
          command: sudo npm install -g npm@9.1.2
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  prettier:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.18.1
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Run prettier
          command: npm run prettier

  test-forge:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.18.1
    resource_class: xlarge
    steps:
      - checkout
      - restore_cache:
          keys:
            - repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Setup env
          command: echo "export PATH=$PATH:$(pwd)/.circleci" >> /home/circleci/.bashrc
      - run:
          name: Finish setting up env
          command: echo "export PATH=$PATH:$(pwd)/.foundry/bin" >> /home/circleci/.bashrc
      - run:
          name: Install Foundry
          command: curl -L https://foundry.paradigm.xyz | bash; source /home/circleci/.bashrc; $HOME/.foundry/bin/foundryup
      - run:
          name: Run tests
          command: |
            source /home/circleci/.bashrc
            export PATH=$PATH:/home/circleci/.foundry/bin; npm run test:unit && npm run test:integration && npm run test:proposals

workflows:
  main:
    jobs:
      - build
      - prettier:
          requires:
            - build
      - test-forge:
          requires:
            - build
